In [79]:
#Equation in cell that begins with 'distance'
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
%matplotlib inline

In [80]:
xTest = []
yTest = []
xTest.append([[1, 2], [8, 12]])
#yTest.append([3, 5])
xTest



[[[1, 2], [8, 12]]]

In [81]:
music = pd.DataFrame()
music['duration'] = [184, 134, 243, 186, 122, 197, 294, 382, 102, 264, 
                     205, 110, 307, 110, 397, 153, 190, 192, 210, 403,
                     164, 198, 204, 253, 234, 190, 182, 401, 376, 102]
music['loudness'] = [18, 34, 43, 36, 22, 9, 29, 22, 10, 24, 
                     20, 10, 17, 51, 7, 13, 19, 12, 21, 22,
                     16, 18, 4, 23, 34, 19, 14, 11, 37, 42]
music['jazz'] = [ 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
                  0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
                  1, 1, 1, 1, 0, 0, 1, 1, 0, 0]
XX =  music[['loudness', 'duration']]
xx = np.array(XX)
xx


array([[ 18, 184],
       [ 34, 134],
       [ 43, 243],
       [ 36, 186],
       [ 22, 122],
       [  9, 197],
       [ 29, 294],
       [ 22, 382],
       [ 10, 102],
       [ 24, 264],
       [ 20, 205],
       [ 10, 110],
       [ 17, 307],
       [ 51, 110],
       [  7, 397],
       [ 13, 153],
       [ 19, 190],
       [ 12, 192],
       [ 21, 210],
       [ 22, 403],
       [ 16, 164],
       [ 18, 198],
       [  4, 204],
       [ 23, 253],
       [ 34, 234],
       [ 19, 190],
       [ 14, 182],
       [ 11, 401],
       [ 37, 376],
       [ 42, 102]], dtype=int64)

In [82]:
xTest[0]

[[1, 2], [8, 12]]

In [83]:
np.linalg.norm(yTest[0]-xTest[0])

IndexError: list index out of range

In [84]:
x = [[2, 5], [3, 5],[101,232],[150,100],[134,34]]
y = [[3, 7]]
InputData = np.array(x)
TestData = np.array(y)

In [85]:
InputData

array([[  2,   5],
       [  3,   5],
       [101, 232],
       [150, 100],
       [134,  34]])

In [86]:
InputData[0]

array([2, 5])

In [87]:
TestData[0]

array([3, 7])

In [88]:
np.linalg.norm(InputData[0]- TestData[0])

2.23606797749979

In [89]:
np.linalg.norm(InputData[1]-TestData[0])

2.0

In [90]:
distances = []
for points in InputData:
    newV = np.linalg.norm(points-TestData[0])
    distances.append(newV)

In [91]:
distances

[2.23606797749979,
 2.0,
 245.41597340026587,
 173.9482681718907,
 133.75350462698165]

In [92]:
# Working for distances of single point to matrix of points

In [93]:
##ya = np.append(ya, [[1, 8]])
#how can i add adata point to array?
#Gives [3, 7, 1, 8]

In [94]:
TestData[0]

array([3, 7])

In [95]:
y

[[3, 7]]

In [96]:
y.append([3, 8])

In [97]:
y

[[3, 7], [3, 8]]

In [98]:
TestData = np.array(y)

In [99]:
TestData

array([[3, 7],
       [3, 8]])

In [100]:
InputData

array([[  2,   5],
       [  3,   5],
       [101, 232],
       [150, 100],
       [134,  34]])

In [105]:
distances = []

#Generate list of all distances for input point 1, 
#sequentially followed by all distances for input point 2, etc.

for points in InputData:
    for ypoints in xx:
        newV = np.linalg.norm(points-ypoints)
        distances.append(newV)
        

#reshape array into sepaarate row for each input (all the distances for each input, 
#next rows all the distances for n remaining inputs
VarDistances = np.reshape(distances, (len(InputData), len(xx)))

min_dist = []
min_loc = []
isjazz = []
#generate list of min 
for minranges in VarDistances:
    min_val = min(minranges)
    index_min = np.argmin(minranges)
    min_dist.append(min_val)
    min_loc.append(index_min)
    isjazz.append(music['jazz'][index_min])
    
    #use np.argmin, or the index location of the minimum matched value 
    #from the test database, to find the corresponding output (0 or 1, Jazz or Rock, etc.)
    
final_df = pd.DataFrame()
final_df['min_dist'] = min_dist
final_df['min_loc'] = min_loc
final_df['is_jazz'] = isjazz
#final_df['IsJazz'] = music['jazz'][final_df.min_loc]
final_df



min_dist  min_loc  is_jazz
0   97.329338        8        1
1   97.252249        8        1
2   59.033889        2        0
3   99.503769       13        0
4  112.538882       13        0

In [22]:
print(min_dist)
print(min_loc)

[2.23606797749979, 2.0]
[0, 0]


In [78]:
x

[[2, 5], [3, 5], [101, 232], [150, 100]]

In [23]:
distances

[2.23606797749979, 3.1622776601683795, 2.0, 3.0]

In [24]:
InputData

array([[2, 5],
       [3, 5]])

In [25]:
TestData

array([[3, 7],
       [3, 8]])

In [31]:
#VarDistances = np.reshape(distances, (len(InputData), len(TestData)))


In [32]:
VarDistances

array([[2.23606798, 3.16227766],
       [2.        , 3.        ]])

In [35]:
VarDistances[1]

array([2., 3.])

In [40]:
min(VarDistances[1])

2.0

array([[ 18, 184],
       [ 34, 134],
       [ 43, 243],
       [ 36, 186],
       [ 22, 122],
       [  9, 197],
       [ 29, 294],
       [ 22, 382],
       [ 10, 102],
       [ 24, 264],
       [ 20, 205],
       [ 10, 110],
       [ 17, 307],
       [ 51, 110],
       [  7, 397],
       [ 13, 153],
       [ 19, 190],
       [ 12, 192],
       [ 21, 210],
       [ 22, 403],
       [ 16, 164],
       [ 18, 198],
       [  4, 204],
       [ 23, 253],
       [ 34, 234],
       [ 19, 190],
       [ 14, 182],
       [ 11, 401],
       [ 37, 376],
       [ 42, 102]], dtype=int64)